extra_street_signs.aliases = {

	["sign_eu_30zone"] = "sign_eu_30_zone",
	["sign_eu_30zoneend"] = "sign_eu_30_zone_end",
	["sign_eu_additionallane"] = "sign_eu_additional_lane",
	["sign_eu_arrowleft"] = "sign_eu_arrow_left",
	["sign_eu_arrowright"] = "sign_eu_arrow_right",
	["sign_eu_arrowshorizontal"] = "sign_eu_arrows_horizontal",
	["sign_eu_arrowsvertical"] = "sign_eu_arrows_vertical",
	["sign_eu_arrowturnleft"] = "sign_eu_arrow_turn_left",
	["sign_eu_arrowturnright"] = "sign_eu_arrow_turn_right",
	["sign_eu_bendleft"] = "sign_eu_bend_left",
	["sign_eu_bendright"] = "sign_eu_bend_right",
	["sign_eu_breakdownbay"] = "sign_eu_break_down_bay",
	["sign_eu_bridlepath"] = "sign_eu_bridle_path",
	["sign_eu_bumpyroad"] = "sign_eu_bumpy_road",
	["sign_eu_busses"] = "sign_eu_buses",
	["sign_eu_busstation"] = "sign_eu_bus_station",
	["sign_eu_curveleft"] = "sign_eu_curve_left",
	["sign_eu_curveright"] = "sign_eu_curve_right",
	["sign_eu_cyclepath"] = "sign_eu_cycle_path",
	["sign_eu_deadendstreet"] = "sign_eu_dead_end_street",
	["sign_eu_deercrossing"] = "sign_eu_deer_crossing",
	["sign_eu_detourend"] = "sign_eu_detour_end",
	["sign_eu_detourleft"] = "sign_eu_detour_left",
	["sign_eu_detourright"] = "sign_eu_detour_right",
	["sign_eu_doublecurveleft"] = "sign_eu_double_curve_left",
	["sign_eu_doublecurveright"] = "sign_eu_double_curve_right",
	["sign_eu_downhillgrade"] = "sign_eu_down_hill_grade",
	["sign_eu_endmajorroad"] = "sign_eu_end_major_road",
	["sign_eu_endnoovertaking"] = "sign_eu_end_no_overtaking",
	["sign_eu_farmanimals"] = "sign_eu_farm_animals",
	["sign_eu_firstaid"] = "sign_eu_first_aid",
	["sign_eu_givewayoncoming"] = "sign_eu_give_way_oncoming",
	["sign_eu_greenarrow"] = "sign_eu_green_arrow",
	["sign_eu_guideboard_left"] = "sign_eu_guide_board_left",
	["sign_eu_guideboard_right"] = "sign_eu_guide_board_right",
	["sign_eu_highwayend"] = "sign_eu_highway_end",
	["sign_eu_intersectionrightofway"] = "sign_eu_intersection_right_of_way",
	["sign_eu_laneshift"] = "sign_eu_lane_shift",
	["sign_eu_leftonly"] = "sign_eu_left_only",
	["sign_eu_leftonly_"] = "sign_eu_left_only_2",
	["sign_eu_majorroad"] = "sign_eu_major_road",
	["sign_eu_mergelanes"] = "sign_eu_merge_lanes",
	["sign_eu_motorroad"] = "sign_eu_motor_road",
	["sign_eu_motorroadend"] = "sign_eu_motor_road_end",
	["sign_eu_nobikes"] = "sign_eu_no_bikes",
	["sign_eu_noentry"] = "sign_eu_no_entry",
	["sign_eu_nohorsebackriding"] = "sign_eu_no_horseback_riding",
	["sign_eu_nomotorcars"] = "sign_eu_no_motor_cars",
	["sign_eu_nomotorvehicles"] = "sign_eu_no_motor_vehicles",
	["sign_eu_noovertaking"] = "sign_eu_no_overtaking",
	["sign_eu_noparking"] = "sign_eu_no_parking",
	["sign_eu_nopedestrians"] = "sign_eu_no_pedestrians",
	["sign_eu_nostopping"] = "sign_eu_no_stopping",
	["sign_eu_notrucks"] = "sign_eu_no_trucks",
	["sign_eu_nouturns"] = "sign_eu_no_uturns",
	["sign_eu_novehicles"] = "sign_eu_no_vehicles",
	["sign_eu_onewayleft"] = "sign_eu_one_way_left",
	["sign_eu_onewayright"] = "sign_eu_one_way_right",
	["sign_eu_parkingsite"] = "sign_eu_parking_site",
	["sign_eu_passingleft"] = "sign_eu_passing_left",
	["sign_eu_passingright"] = "sign_eu_passing_right",
	["sign_eu_pedestriancrossing"] = "sign_eu_pedestrian_crossing",
	["sign_eu_pedestriansleft"] = "sign_eu_pedestrians_left",
	["sign_eu_pedestriansright"] = "sign_eu_pedestrians_right",
	["sign_eu_pedestrianszone"] = "sign_eu_pedestrians_zone",
	["sign_eu_pedestrianszoneend"] = "sign_eu_pedestrians_zone_end",
	["sign_eu_priooveroncoming"] = "sign_eu_prio_over_oncoming",
	["sign_eu_railroadcrossing"] = "sign_eu_railroad_crossing",
	["sign_eu_rightofway"] = "sign_eu_right_of_way",
	["sign_eu_rightonly"] = "sign_eu_right_only",
	["sign_eu_rightonly_"] = "sign_eu_right_only_2",
	["sign_eu_roadnarrowsboth"] = "sign_eu_road_narrows_both",
	["sign_eu_roadnarrowsleft"] = "sign_eu_road_narrows_left",
	["sign_eu_roadnarrowsright"] = "sign_eu_road_narrows_right",
	["sign_eu_roadworks"] = "sign_eu_road_works",
	["sign_eu_seperatedpedestriansbicyclists"] = "sign_eu_seperated_pedestrians_bicyclists",
	["sign_eu_sharedpedestriansbicyclists"] = "sign_eu_shared_pedestrians_bicyclists",
	["sign_eu_slipdanger"] = "sign_eu_slip_danger",
	["sign_eu_standrews"] = "sign_eu_st_andrews",
	["sign_eu_straightleftonly"] = "sign_eu_straight_left_only",
	["sign_eu_straightonly"] = "sign_eu_straight_only",
	["sign_eu_straightrightonly"] = "sign_eu_straight_right_only",
	["sign_eu_trafficcalmingarea"] = "sign_eu_traffic_calming_area",
	["sign_eu_trafficcalmingareaend"] = "sign_eu_traffic_calming_area_end",
	["sign_eu_trafficlightahead"] = "sign_eu_traffic_lights_ahead",
	["sign_eu_transfertoothercarriageway1"] = "sign_eu_transfer_to_other_carriageway_1",
	["sign_eu_transfertoothercarriageway2"] = "sign_eu_transfer_to_other_carriageway_2",
	["sign_eu_turningprioroad3_1"] = "sign_eu_turning_prio_road_3_1",
	["sign_eu_turningprioroad3_2"] = "sign_eu_turning_prio_road_3_2",
	["sign_eu_turningprioroad4"] = "sign_eu_turning_prio_road_4",
	["sign_eu_twowaytraffic"] = "sign_eu_two_way_traffic",
	["sign_eu_uphillgrade"] = "sign_eu_up_hill_grade",

}

for k,v in pairs(extra_street_signs.aliases) do
	core.register_alias("extra_street_signs:" .. k, "extra_street_signs:" .. v)
	core.register_alias("extra_street_signs:" .. k .. "_polemount", "extra_street_signs:" .. v .. "_polemount")
	core.register_alias("streets:" .. k, "extra_street_signs:" .. v)
	core.register_alias("streets:" .. k .. "_polemount", "extra_street_signs:" .. v .. "_polemount")
end

if core.get_modpath("street_signs") then
	core.register_alias("extra_street_signs:sign_eu_stop", "street_signs:sign_stop")
end
